<?php

namespace Application\Sonata\MediaBundle\Entity;

use Sonata\MediaBundle\Entity\BaseMedia as BaseMedia;
use MotogpBundle\Entity\Post;
use Doctrine\ORM\Mapping as ORM;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 */
class PostMedia extends BaseMedia
{

    public function __construct()
    {
        $this->context        = 'imagenes';
        $this->providerName   = 'sonata.media.provider.image';
        $this->providerStatus = 1;
        $this->providerReference = "reference";
        $this->providerMetadata = [];
        
        $this->name           = 'post-image-'.(new \DateTime())->format('ymdms');


//        $media->setBinaryContent($url);
//        $media->setProviderName('sonata.media.provider.image');
//
//        $this->getContainer()->get('sonata.media.manager.media')->save($media);
//
//        $instance->addMedia($media);

    }

    /**
     * @var int $id
     */
    protected $id;


    /**
     * Get id.
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @var Post
     *
     * @ORM\ManyToOne(targetEntity="Post", inversedBy="medias")
     * @ORM\JoinColumns({
     *     @ORM\JoinColumn(name="post", referencedColumnName="id")
     * })
     */
    private $post;

    /**
     * @return Post
     */
    public function getPost()
    {
        return $this->post;
    }

    /**
     * @param Post $post
     */
    public function setPost($post)
    {
        $this->post = $post;
    }

    
}
