imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: sonata.yml }
    - { resource: api-platform/config.yml }
    - { resource: "@MotogpBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es

framework:
    #esi: ~
    translator: ~
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        kernelRootDir: "%kernel.root_dir%"
    form_themes:
        - '@SonataFormatter/Form/formatter.html.twig'
        - 'SonataCoreBundle:Form:datepicker.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: true
#        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: true
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    #ApplicationSonataMediaBundle: ~
                    SonataMediaBundle: ~


# Swiftmailer Configuration
swiftmailer:
    default_mailer: mailer
    mailers:
        mailer:
            transport: '%mailer_transport%'
            host: '%mailer_host%'
            username: '%mailer_user%'
            password: '%mailer_password%'
            port: 465
            encryption: ssl
            spool: { type: memory }
        mailer_contact:
            transport: '%mailer_contact_transport%'
            host: '%mailer_contact_host%'
            username: '%mailer_contact_user%'
            password: '%mailer_contact_password%'
            port: '%mailer_contact_port%'
            encryption: '%mailer_contact_encryption%'
            spool: { type: memory }
            stream_options:
                ssl:
                    allow_self_signed: true
                    verify_peer: false
                    verify_peer_name: false


assetic:
    debug: '%kernel.debug%'
    use_controller: true
    filters:
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"


sonata_block:
    default_contexts: [sonata_page_bundle]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.rss:

        # Some specific block from the SonataMediaBundle
#        sonata.media.block.media:
#        sonata.media.block.gallery:
#        sonata.media.block.feature_media:

        # Some block with different templates
        #acme.demo.block.demo:
        #    templates:
        #       - { name: 'Simple', template: '@AcmeDemo/Block/demo_simple.html.twig' }
        #       - { name: 'Big',    template: '@AcmeDemo/Block/demo_big.html.twig' }


ivory_ck_editor:
    default_config: my_config
    configs:
        my_config:
            toolbar: [[ "Format", "Bold", "Italic", "Underline", "Strike", "size",'FontSize', 'TextColor', "Subscript", "Superscript", "-", "RemoveFormat", "NumberedList", "BulletedList", "-", "JustifyLeft","JustifyCenter","JustifyRight","JustifyBlock", "Outdent", "Indent", "-", "Blockquote" , "Link", "Unlink" ]]
            language: 'es'
            format_tags: 'p;h1;h2;h3;h4;h5;h6;div'


oneup_uploader:
      mappings :
         gallery :
             frontend : dropzone
             root_folder: true


liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache : ~
        email_thumbnail :
            quality : 70
            filters :
                thumbnail: { size : [222, 222], mode: outbound}
        email_thumbnail_right :
                    quality : 70
                    filters :
                        thumbnail: { size : [222, 222], mode: outbound}
                        background : { size : [237, 222], position : left, color : '#FFFFFF' }
        email_header :
            format: png
            quality : 70
            filters:
                relative_resize:
                    widen : 948