index:
    locales: { "es": "/es", "en": "/en" }
    defaults: { _controller: MotogpBundle:Public:index }

motogp_public_index:
    locales: { "es": "/es", "en": "/en" }
    defaults: { _controller: MotogpBundle:Public:index }

images:
    locales: { "es": "/es/imagenes", "en": "/en/images" }
    defaults: { _controller: MotogpBundle:Public:images }

videos:
    locales: { "es": "/es/videos", "en": "/en/videos" }
    defaults: { _controller: MotogpBundle:Public:videos }

motos:
    locales: { "es": "/es/ducati", "en": "/en/ducati" }
    defaults: { _controller: MotogpBundle:Public:motos }

riders:
    locales: { "es": "/es/piloto/{id}", "en": "/en/rider/{id}" }
    defaults: { _controller: MotogpBundle:Public:riders }

sponsors:
    locales: { "es": "/es/sponsors", "en": "/en/sponsors" }
    defaults: { _controller: MotogpBundle:Public:sponsors }

sponsor:
    locales: { "es": "/es/sponsor/{id}", "en": "/en/sponsor/{id}" }
    defaults: { _controller: MotogpBundle:Public:sponsor }

posts:
    locales: { "es": "/es/noticias", "en": "/en/news" }
    defaults: { _controller: MotogpBundle:Public:posts }

post:
    locales: { "es": "/es/noticias/{id}", "en": "/en/news/{id}" }
    defaults: { _controller: MotogpBundle:Public:post}

team_staff:
    locales: { "es": "/es/equipo", "en": "/en/team-staff" }
    defaults: { _controller: MotogpBundle:Public:team}

public_contact:
    locales: { "en": "/en/contact", "es": "/es/contacto" }
    defaults: { _controller: MotogpBundle:Contact:contactForm}