index:
    locales: { "es": "/es/{modality}", "en": "/en/{modality}" }
    defaults: { _controller: MotogpBundle:Public:index }

motogp_public_index:
    locales: { "es": "/es/{modality}", "en": "/en/{modality}" }
    defaults: { _controller: MotogpBundle:Public:index }

images:
    locales: { "es": "/es/{modality}/imagenes", "en": "/en/{modality}/images" }
    defaults: { _controller: MotogpBundle:Public:images }

videos:
    locales: { "es": "/es/{modality}/videos", "en": "/en/{modality}/videos" }
    defaults: { _controller: MotogpBundle:Public:videos }

motos:
    locales: { "es": "/es/{modality}/motos", "en": "/en/{modality}/motos" }
    defaults: { _controller: MotogpBundle:Public:motos }

riders:
    locales: { "es": "/es/{modality}/piloto/{id}", "en": "/en/{modality}/rider/{id}" }
    defaults: { _controller: MotogpBundle:Public:riders }

sponsors:
    locales: { "es": "/es/{modality}/sponsors", "en": "/en/{modality}/sponsors" }
    defaults: { _controller: MotogpBundle:Public:sponsors }

sponsor:
    locales: { "es": "/es/{modality}/sponsor/{id}", "en": "/en/{modality}/sponsor/{id}" }
    defaults: { _controller: MotogpBundle:Public:sponsor }

posts:
    locales: { "es": "/es/{modality}/noticias", "en": "/en/{modality}/news" }
    defaults: { _controller: MotogpBundle:Public:posts }

post:
    locales: { "es": "/es/{modality}/noticias/{id}", "en": "/en/{modality}/news/{id}" }
    defaults: { _controller: MotogpBundle:Public:post}

team_staff:
    locales: { "es": "/es/{modality}/equipo", "en": "/en/{modality}/team-staff" }
    defaults: { _controller: MotogpBundle:Public:team}

public_contact:
    locales: { "en": "/en/{modality}/contact", "es": "/es/{modality}/contacto" }
    defaults: { _controller: MotogpBundle:Contact:contactForm}

public_contact_success:
    locales: { "en": "/en/{modality}/contact/success", "es": "/es/{modality}/contacto/enviado" }
    defaults: { _controller: MotogpBundle:Contact:contactFormSuccess}