index:
    locales: { "es": "/es/{modality}", "en": "/en/{modality}" }
    defaults: { _controller: MotogpBundle:Public:index, modality : '' }

motogp_public_index:
    locales: { "es": "/es/{modality}", "en": "/en/{modality}" }
    defaults: { _controller: MotogpBundle:Public:index }

images:
    locales: { "es": "/es/{modality}/imagenes", "en": "/en/{modality}/images" }
    defaults: { _controller: MotogpBundle:Public:images }

videos:
    locales: { "es": "/es/{modality}/videos", "en": "/en/{modality}/videos" }
    defaults: { _controller: MotogpBundle:Public:videos }

motos:
    locales: { "es": "/es/{modality}/motos", "en": "/en/{modality}/motos" }
    defaults: { _controller: MotogpBundle:Public:motos }

riders:
    locales: { "es": "/es/{modality}/piloto/{slug}", "en": "/en/{modality}/rider/{slug}" }
    defaults: { _controller: MotogpBundle:Public:riders }

partners:
    locales: { "es": "/es/{modality}/partners", "en": "/en/{modality}/partners" }
    defaults: { _controller: MotogpBundle:Public:sponsors }

partner:
    locales: { "es": "/es/{modality}/partner/{slug}", "en": "/en/{modality}/partner/{slug}" }
    defaults: { _controller: MotogpBundle:Public:sponsor }

posts:
    locales: { "es": "/es/{modality}/noticias", "en": "/en/{modality}/news" }
    defaults: { _controller: MotogpBundle:Public:posts }

post:
    locales: { "es": "/es/{modality}/noticias/{slug}", "en": "/en/{modality}/news/{slug}" }
    defaults: { _controller: MotogpBundle:Public:post}

team_staff:
    locales: { "es": "/es/{modality}/equipo", "en": "/en/{modality}/team-staff" }
    defaults: { _controller: MotogpBundle:Public:team}

public_contact:
    locales: { "en": "/en/{modality}/contact", "es": "/es/{modality}/contacto" }
    defaults: { _controller: MotogpBundle:Contact:contactForm}

public_register:
    locales: { "en": "/en/{modality}/register", "es": "/es/{modality}/registro" }
    defaults: { _controller: MotogpBundle:Newsletters:registerForm}

public_contact_success:
    locales: { "en": "/en/{modality}/contact/success", "es": "/es/{modality}/contacto/enviado" }
    defaults: { _controller: MotogpBundle:Contact:contactFormSuccess}

public_register_success:
    locales: { "en": "/en/{modality}/register/success", "es": "/es/{modality}/registro/completado" }
    defaults: { _controller: MotogpBundle:Newsletters:registerFormSuccess}

public_register_confirmation:
    locales: { "en": "/en/{modality}/register/confirm", "es": "/es/{modality}/registro/confirmacion" }
    defaults: { _controller: MotogpBundle:Newsletters:confirmFormSuccess}

cookies:
    locales: { "en": "/en/{modality}/cookies", "es": "/es/{modality}/cookies" }
    defaults: { _controller: MotogpBundle:Public:cookies}

privacy:
    locales: { "en": "/en/{modality}/privacy", "es": "/es/{modality}/politica-de-privacidad" }
    defaults: { _controller: MotogpBundle:Public:privacy}

terms:
    locales: { "en": "/en/{modality}/terms-and-conditions", "es": "/es/{modality}/terminos-y-condiciones" }
    defaults: { _controller: MotogpBundle:Public:terms}

newsletters_unsubscribe:
    locales: { "en": "/en/{modality}/unsubscribe", "es": "/es/{modality}/baja-newsletters" }
    defaults: { _controller: MotogpBundle:Newsletters:requestUnsubscribe}

newsletters_unsubscribe_confirmation:
    locales: { "en": "/en/{modality}/unsubscribe-confirm", "es": "/es/{modality}/confirmacion-baja-newsletters" }
    defaults: { _controller: MotogpBundle:Newsletters:confirmUnsubscription }


