<?php

namespace MotogpBundle\Repository;

/**
 * BuilderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuilderRepository extends \Doctrine\ORM\EntityRepository
{
}
