<?php

namespace MotogpBundle\Repository;

/**
 * CustomerGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
