<?php

namespace MotogpBundle\Repository;

/**
 * CustomerTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
