<?php

namespace MotogpBundle\Repository;

/**
 * GalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getGalleries()
    {
        return $this->createQueryBuilder('g')
            ->where('g.slug IS NULL')
            ->getQuery()
            ->getResult()
            ;
    }
}
