<?php

namespace MotogpBundle\Repository;

/**
 * GalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getGalleries()
    {
        return $this->createQueryBuilder('g')
            ->where('g.slug IS NULL')
            ->orderBy('g._order', 'ASC')
            ->getQuery()
            ->getResult()
            ;
    }

    public function findAllLastGalleries()
    {
        return $this->createQueryBuilder('g')
            ->where('g.slug IS NULL')
            ->orderBy('g.createdAt', 'ASC')
            ->getQuery()
            ->getResult()
            ;
    }

    public function findAllLastRiderGalleries($rider)
    {
        return $this->createQueryBuilder('g')
            ->where('g.rider = :rider')
            ->orderBy('g.createdAt', 'ASC')
            ->setParameter('rider', $rider->getId())
            ->getQuery()
            ->getResult()
            ;
    }
}
