<?php

namespace MotogpBundle\Repository;

/**
 * GalleryMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryMediaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllLastRiderMedia($rider)
    {
        return $this->createQueryBuilder('g')
            ->where('g.rider = :rider')
            ->orderBy('g.createdAt', 'DESC')
            ->setParameter('rider', $rider->getId())
            ->getQuery()
            ->getResult()
            ;
    }
}
