<?php

namespace MotogpBundle\Repository;

/**
 * GeneralConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneralConfigurationRepository extends \Doctrine\ORM\EntityRepository
{
}
