<?php

namespace MotogpBundle\Repository;

/**
 * ModalityClassificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModalityClassificationRepository extends \Doctrine\ORM\EntityRepository
{
}
