<?php

namespace MotogpBundle\Repository;

/**
 * MotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotoRepository extends \Doctrine\ORM\EntityRepository
{
}
