<?php

namespace MotogpBundle\Repository;

/**
 * NewsletterMailInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterMailInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
