<?php

namespace MotogpBundle\Repository;

/**
 * NewsletterHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
