<?php

namespace MotogpBundle\Repository;

/**
 * NewsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterRepository extends \Doctrine\ORM\EntityRepository
{
    public function getQueued()
    {
        return $this->createQueryBuilder('n')
            ->where('n.queued = true')
            ->getQuery()
            ->getResult()
            ;
    }
}
