<?php

namespace MotogpBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLast()
    {
        return $this->findBy(array(), array('publishedAt' => 'DESC'));
    }
}
