<?php

namespace MotogpBundle\Repository;

/**
 * RiderTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RiderTeamRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMain()
    {
        return $this->createQueryBuilder('r')
            ->where('r.main = true')
            ->orderBy('r._order','ASC')
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }
}
