<?php

namespace MotogpBundle\Repository;

/**
 * RiderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RiderRepository extends \Doctrine\ORM\EntityRepository
{
}
