<?php

namespace MotogpBundle\Repository;

/**
 * RiderChampionshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RiderChampionshipRepository extends \Doctrine\ORM\EntityRepository
{
}
