<?php

namespace MotogpBundle\Repository;

/**
 * RiderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RiderRepository extends \Doctrine\ORM\EntityRepository
{
    public function findInternalRiders()
    {
        return $this->createQueryBuilder('r')
            ->innerJoin('r.riderTeam', 'rt')
            ->where('rt.main IS NOT NULL')
            ->getQuery()
            ->getResult()
            ;
    }

    public function findHomeRiders()
    {
        return $this->createQueryBuilder('r')
            ->where('r.showInHome = true')
            ->orderBy('r._order','ASC')
            ->getQuery()
            ->getResult()
            ;
    }
}
