<?php

namespace MotogpBundle\Repository;

/**
 * RiderTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RiderTeamRepository extends \Doctrine\ORM\EntityRepository
{
}
