<?php

namespace MotogpBundle\Repository;

/**
 * ScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScoreRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLast()
    {
        return $this->findBy(array(), array('publishedAt' => 'DESC'));
    }

    public function getLastByModality($modality) {

        return $this->createQueryBuilder('s')
            ->leftJoin('s.race', 'r')
            ->where('r.modality = :modality')
            ->setParameter('modality', $modality->getId())
            ->getQuery()
            ->getResult()
            ;


//        ->leftJoin('doc.uploadedBy', 'u')
//            ->where('doc.company = :company')
//            ->andWhere('u.deletedAt IS NULL')
//            ->andWhere('doc.deletedAt IS NULL')
//            ->andWhere('doc.type IN (:types)')
    }

}
