<?php

namespace MotogpBundle\Repository;

/**
 * ScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScoreRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLast()
    {
        return $this->findBy(array(), array('publishedAt' => 'DESC'));
    }
}
