<?php

namespace MotogpBundle\Repository;

/**
 * SponsorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SponsorRepository extends \Doctrine\ORM\EntityRepository
{

    public function findColor()
    {
        return $this->createQueryBuilder('s')
            ->where('s.bn != true')
            ->getQuery()
            ->getResult()
            ;
    }

    public function findBN()
    {
        return $this->createQueryBuilder('s')
            ->where('s.bn = true')
            ->getQuery()
            ->getResult()
            ;
    }

}
