<?php

namespace MotogpBundle\Repository;

/**
 * TeamQuotationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamQuotationRepository extends \Doctrine\ORM\EntityRepository
{
}
