<?php

namespace MotogpBundle\Repository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllInModality($modality)
    {

        return $this->createQueryBuilder('s')
            ->join('s.modalities', 'm')
            ->where('m.id = :modality')
            ->setParameter('modality', $modality->getId())
            ->getQuery()
            ->getResult()
            ;
    }
}
