<?php

namespace MotogpBundle\Repository;

/**
 * TrackRecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackRecordRepository extends \Doctrine\ORM\EntityRepository
{
}
