services:
    motogp.admin.post:
        class: MotogpBundle\Admin\PostAdmin
        arguments: [~, MotogpBundle\Entity\Post, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Blog, label: Post }
        public: true



    motogp.admin.video:
        class: MotogpBundle\Admin\VideoAdmin
        arguments: [~, MotogpBundle\Entity\Video, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Multimedia, label: Video }
        public: true

    motogp.admin.rider_team:
        class: MotogpBundle\Admin\RiderTeamAdmin
        arguments: [~, MotogpBundle\Entity\RiderTeam, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Equipo, label: Equipos }
        public: true

    motogp.admin.rider:
        class: MotogpBundle\Admin\RiderAdmin
        arguments: [~, MotogpBundle\Entity\Rider, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Equipo, label: Corredores }
        public: true

    motogp.admin.team:
        class: MotogpBundle\Admin\TeamAdmin
        arguments: [~, MotogpBundle\Entity\Team, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Equipo, label: Staff }
        public: true

    motogp.admin.category:
        class: MotogpBundle\Admin\CategoryAdmin
        arguments: [~, MotogpBundle\Entity\Category, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Configuración, label: Tags }
        public: true

    motogp.admin.modality:
        class: MotogpBundle\Admin\ModalityAdmin
        arguments: [~, MotogpBundle\Entity\Modality, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Configuración, label: Modality }
        public: true


    motogp.admin.team_category:
        class: MotogpBundle\Admin\TeamCategoryAdmin
        arguments: [~, MotogpBundle\Entity\TeamCategory, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Configuración, label: Categorías staff }
        public: true

    motogp.admin.builder:
        class: MotogpBundle\Admin\BuilderAdmin
        arguments: [~, MotogpBundle\Entity\Builder, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Configuración, label: Constructores }
        public: true

    motogp.admin.circuit:
        class: MotogpBundle\Admin\CircuitAdmin
        arguments: [~, MotogpBundle\Entity\Circuit, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Configuración, label: Circuitos }
        public: true

    motogp.admin.sponsor:
        class: MotogpBundle\Admin\SponsorAdmin
        arguments: [~, MotogpBundle\Entity\Sponsor, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Configuración, label: Sponsors }
        public: true

    motogp.admin.moto:
        class: MotogpBundle\Admin\MotoAdmin
        arguments: [~, MotogpBundle\Entity\Moto, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Configuración, label: Moto }
        public: true

    motogp.admin.race:
        class: MotogpBundle\Admin\RaceAdmin
        arguments: [~, MotogpBundle\Entity\Race, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Carreras, label: Carreras }
        public: true

    motogp.admin.season:
            class: MotogpBundle\Admin\SeasonAdmin
            arguments: [~, MotogpBundle\Entity\Season, SonataAdminBundle:CRUD]
            tags:
                - { name: sonata.admin, manager_type: orm, group: Carreras, label: Temporadas }
            public: true

    motogp.admin.score:
        class: MotogpBundle\Admin\ScoreAdmin
        arguments: [~, MotogpBundle\Entity\Score, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Score, show_in_dashboard: false }
        public: true


    motogp.admin.post_media:
        class: Application\Sonata\MediaBundle\Admin\PostMediaAdmin
        arguments: [~, Application\Sonata\MediaBundle\Entity\PostMedia, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: PostMedia }
        public: true
