services:
    app.upload_listener:
        class: AppBundle\EventListener\UploadListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }

    motogp.admin.post:
        class: MotogpBundle\Admin\PostAdmin
        arguments: [~, MotogpBundle\Entity\Post, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Blog, label: Publicaciones }
        public: true

    motogp.admin.rider:
        class: MotogpBundle\Admin\RiderAdmin
        arguments: [~, MotogpBundle\Entity\Rider, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Equipo, label: Pilotos }
        public: true


    motogp.admin.rider_external:
        class: MotogpBundle\Admin\RiderExternalAdmin
        arguments: [~, MotogpBundle\Entity\Rider, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Equipo, label: Pilotos externos }
        public: true

    motogp.admin.team:
        class: MotogpBundle\Admin\TeamAdmin
        arguments: [~, MotogpBundle\Entity\Team, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Staff, label: Staff }
        public: true


    motogp.admin.team_category:
            class: MotogpBundle\Admin\TeamCategoryAdmin
            arguments: [~, MotogpBundle\Entity\TeamCategory, SonataAdminBundle:CRUD]
            tags:
                - { name: sonata.admin, manager_type: orm, group: Staff, label: Categorías staff }
            public: true

    motogp.admin.race:
        class: MotogpBundle\Admin\RaceAdmin
        arguments: [~, MotogpBundle\Entity\Race, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Carreras, label: Carreras }
        public: true

    motogp.admin.season:
            class: MotogpBundle\Admin\SeasonAdmin
            arguments: [~, MotogpBundle\Entity\Season, SonataAdminBundle:CRUD]
            tags:
                - { name: sonata.admin, manager_type: orm, group: Carreras, label: Temporadas }
            public: true

    motogp.admin.gallery:
        class: MotogpBundle\Admin\GalleryAdmin
        arguments: [~, MotogpBundle\Entity\Gallery, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Multimedia, label: Galerías }
        public: true

    motogp.admin.slider:
            class: MotogpBundle\Admin\SliderAdmin
            arguments: [~, MotogpBundle\Entity\Gallery, SonataAdminBundle:CRUD]
            tags:
                - { name: sonata.admin, manager_type: orm, group: Multimedia, label: Sliders }
            public: true

    motogp.admin.video:
        class: MotogpBundle\Admin\VideoAdmin
        arguments: [~, MotogpBundle\Entity\Video, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Multimedia, label: Vídeos }
        public: true


    motogp.admin.customer:
        class: MotogpBundle\Admin\CustomerAdmin
        arguments: [~, MotogpBundle\Entity\Customer, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Newsletters, label: Usuarios }
        public: true

    motogp.admin.rider_team_external:
        class: MotogpBundle\Admin\RiderTeamExternalAdmin
        arguments: [~, MotogpBundle\Entity\RiderTeam, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Configuración, label: Equipo externo }
        public: true

    motogp.admin.category:
        class: MotogpBundle\Admin\CategoryAdmin
        arguments: [~, MotogpBundle\Entity\Category, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Configuración, label: Tags, show_in_dashboard: false }

    motogp.admin.modality:
        class: MotogpBundle\Admin\ModalityAdmin
        arguments: [~, MotogpBundle\Entity\Modality, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Configuración, label: Modality }
        public: true




    motogp.admin.builder:
        class: MotogpBundle\Admin\BuilderAdmin
        arguments: [~, MotogpBundle\Entity\Builder, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Configuración, label: Constructores }
        public: true

    motogp.admin.circuit:
        class: MotogpBundle\Admin\CircuitAdmin
        arguments: [~, MotogpBundle\Entity\Circuit, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Configuración, label: Circuitos }
        public: true

    motogp.admin.sponsor:
        class: MotogpBundle\Admin\SponsorAdmin
        arguments: [~, MotogpBundle\Entity\Sponsor, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Configuración, label: Sponsors }
        public: true

    motogp.admin.moto:
        class: MotogpBundle\Admin\MotoAdmin
        arguments: [~, MotogpBundle\Entity\Moto, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Configuración, label: Motos }
        public: true


    motogp.admin.score:
        class: MotogpBundle\Admin\ScoreAdmin
        arguments: [~, MotogpBundle\Entity\Score, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Score, show_in_dashboard: false }
        public: true

    motogp.admin.post_media:
        class: Application\Sonata\MediaBundle\Admin\PostMediaAdmin
        arguments: [~, Application\Sonata\MediaBundle\Entity\PostMedia, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: PostMedia, show_in_dashboard: false }
        public: true

    motogp.admin.gallery_media:
        class: Application\Sonata\MediaBundle\Admin\GalleryMediaAdmin
        arguments: [~, Application\Sonata\MediaBundle\Entity\GalleryMedia, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: GalleryMedia, show_in_dashboard: false }
        public: true

    motogp.admin.featured_media:
        class: Application\Sonata\MediaBundle\Admin\FeaturedMediaAdmin
        arguments: [~, Application\Sonata\MediaBundle\Entity\FeaturedMedia, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: FeaturedMedia, show_in_dashboard: false }
        public: true

    motogp.admin.logo:
        class: Application\Sonata\MediaBundle\Admin\LogoAdmin
        arguments: [~, Application\Sonata\MediaBundle\Entity\Logo, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Logo, show_in_dashboard: false}
        public: true

    motogp.admin.homeimage:
        class: Application\Sonata\MediaBundle\Admin\HomeImageAdmin
        arguments: [~, Application\Sonata\MediaBundle\Entity\HomeImage, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Logo, show_in_dashboard: false}
        public: true

    motogp.admin.rider_team:
        class: MotogpBundle\Admin\RiderTeamAdmin
        arguments: [~, MotogpBundle\Entity\RiderTeam, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Configuración, label: Equipo }
        public: true

    motogp.admin.track_record:
        class: MotogpBundle\Admin\TrackRecordAdmin
        arguments: [~, MotogpBundle\Entity\TrackRecord, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: TrackRecord, show_in_dashboard: false }
        public: true
